language: node_js
node_js:
- '5.0'
- 'stable'
sudo: false
branches:
  except:
  - "/^v[0-9\\.]+/"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
    - CXX=g++-4.8
    - secure: bd5uSwYFElJTMRntn9qGRr+zNdDD7j338CZ110mvs21uzF7L+vpK7kQPvrWs+qeZj2cG2LidkhFQjvhhtaDuf1yRKzXuWPEZ8quCH/S5Kv2JBSXVCbTkMvjKHvSVNrlm8vYtxbxEuJZPd/8KWvnlSZSgBmmUMSKPnZIJeMaoKMnhjTrDonYzClIUpCqtyLqxp7S0TscZKnX12kuNfVY9m8b2EnbnKodzJbABGLmpk+TDXjZZ2TS+W0qBZ/z8S6wSslX3XLN0a+3QLc3JF3+j8tojnlQsqzwxcUn4QYgjzx71LHuShEHNEZLR03chBe+/sLNuuOqODyg5R2t+X6qqSvjf93QpJIiJDKhCdh2hKix5NRhrTP1Ghkt3/jbBmbP+FeOI2O+GrbJRItvzEWTxHev7qsC6cJcnLuMyNqrvD4QNn2Ex9bV+qYeShCqLbxI4xwNMeJPJKlEmM2NTjBSqSi0f+p0r0vT8cbwLsIXaLHqj0mLQhoGnFl/YRA8ytPGUeK2xCjL5HKJSxgxUQB1Y2IRrMdAQ6ll24JGHvq4RHlEIMeZoAVGTeT9OgtZ8MMtYP6iZc9VQ/HHo+epgWMC6biJv4nRISNykuz79S3pYLDgnehLvGtmbBlxXY2o+kwQG2x3i57oxOSiv8ZT6mBOxbFajn4G27Od2tey+Vfnc/bU=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
  - env: EMBER_TRY_SCENARIO=ember-beta
before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper
- pr-bumper check
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
install:
- npm install
- bower install
script:
- npm run lint
- ember try:one $EMBER_TRY_SCENARIO --- ember test
after_success:
- .travis/publish-coverage.sh
before_deploy:
- pr-bumper bump
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: D1cVdDw0Gjv/0f+C5T/xFwUMFCmz8eF5g2Wqh/LUGwPV3/0fY/n0babr2C/E6w1BSMlEmWKAjbgQkCGgHRgVkjHQK8e/lnhEyc7pmTiDyMxD3XM0XJuZvJoQ9s16WkH7joUOVfKRKQCM/iIVKm9m/dqC1w0iw5FoN0HrE8aBG1f6ioTQaqcjrsqKcPPi4NtllsM4qDEktPvOICehzxK6z1PllT2HEoFNHYUxlWOFiaXlfYgCI6OhZDVbIxvNJ3IqcMmPnuX4w+Fe/MSxN4TuTaz942Z8U4SuvetcZQOF2mWyLefXHvWA4PItjVttY0SiwAZk8XIL1B07Bq7aofsTNyFEu8tjw5E2qIM2pyt9+r4/0cKZNiHmzAYupOzZzOmhKAzIvsK4VpgK+5ElO6S+B4FCCx3cI7kS/pwRlI3aAqoGTEloByt79qbwyQNFsE4DrjKhPCrYwI52aBwkvw7ygLb9Ioh6HEyWEFvdN9EVR6WxKdnwhCq0cQ23ba3T5BkcijazTUqRinHhDnsF5uSUGW5CeF7LAOu1hat2MDkMXWqoqM/l564g3ixPi+/r3SYH4JMjkvyst/4HnN6l62bDmPvb2SMaHC5/Enxl6gJgYuVyRfgaMGIeHLyqCFR+ThO1TwlAYwRDv8q5ixStvZ3cj/+3/4NuCvR9ZcscT7OTaPo=
  on:
    branch: master
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: 'stable'
    tags: false
after_deploy:
- .travis/publish-gh-pages.sh
notifications:
  slack:
    secure: fCu8i1J0H+6PTRtQswzIJA19rSddhnskGp5F3Iqo+QtXpgPD0JRAPgIf6drBzxy8IvdxrhwwkAhgmEmpfUxoVEMTVWEtVSm3l0Kccy6dMi0EC357WhQNCcgavLnXkKEPggmJgArmyHoxnKR5ZykyO5BKZ9FThCc/nPlKfjdrPxyeqS3PdXwnmZMgGwSLH3GuSVnZ0mxwls1RgYH2JI+quqBifCIZIxkGnL5eVMxLrhK1K2GRNePHeALTa4LFJqWPxjIL/1iP6CfvazihrNCCWu2bgI72vvMFXnGYD+6OmVrGbaYNUtzzQJ6+UZpHfG7o3UhiJECKJMgX+wEHSpnoGPnqMpXC3RN0/BWNf6YAiCSIU59CMJ8y8/UVVepXnLsL/8zvvhDzPG/Bs7HkhyYNT+PI0zIJ5P4dpJoXi02u0XYhP72bz+qtwhCx2659/0CYJhOMZLFrzL+53zjmgNPw4OzIOTOAA9dwC0OYTj16mCDcATAmCYdomvjgrZCA6gxQUL/sCnn34Ba253/o3g9oGsPYnmArqqRirSP0NC6k9F85xj+sQDhkcQHBgap86L1u2NoUhAMtGxpi0UsjLwHW2jfOX+vbZUCGsK9BHLBo5T4Sc+Yg5t9CQQCrdTfKRZF6PjhEZjY3bD/9wDNgNH/KjafLLuF2zGRZdPToeEeKj5w=
